server:
  port: 8092

spring:
  config:
    name: dubbo-consumer-example

dubbo:
  application:
    name: dubbo-consumer-example
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881